services:
  app:
    image: ${DOCKERHUB_USERNAME}/server:latest
    container_name: server-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-redis}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT:-6379}
    depends_on:
      - redis
    env_file: ./.env
    ports:
      - "127.0.0.1:28080:8080"
    networks: [ proxy ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 20s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks: [ proxy ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  redis-data:
